services:
  gateway:
      build:
        context: ./market
        dockerfile: ./gateway/Dockerfile
      container_name: gateway
      environment:
        GATEWAY_CONFIG: ./configs/config.yaml
      ports:
      - "8080:8080"
      restart: "no"