services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vite_frontend
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - gateway
    ports:
      - "3000:80"
    restart: "unless-stopped"

  gateway:
    build:
      context: ./market
      dockerfile: ./gateway/Dockerfile
    container_name: gateway
    environment:
      SERVICE_CONFIG_PATH: ./configs/config.yaml
    ports:
    - "8080:8080"
    restart: "no"

  product:
    build:
      context: ./market
      dockerfile: ./product_service/Dockerfile
    container_name: product_service
    environment:
      SERVICE_CONFIG_PATH: ./configs/config.yaml
    depends_on:
      - products_db
    restart: "always"
  
  products_db:
    image: postgres:14-alpine
    container_name: products_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: products
    ports:
      - "5433:5432"
    volumes:
      - products_db_data:/var/lib/postgresql/data
      - ./market/database/product:/docker-entrypoint-initdb.d
    restart: "always"

  auth:
    build:
      context: ./market
      dockerfile: ./auth_service/Dockerfile
    container_name: auth_service
    environment:
      SERVICE_CONFIG_PATH: ./configs/config.yaml
    depends_on:
      - auth_db
    restart: "always"

  auth_db:
    image: postgres:14-alpine
    container_name: auth_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: auth
    ports:
      - "5432:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data
      - ./market/database/auth:/docker-entrypoint-initdb.d
    restart: "always"

  order:
    build:
      context: ./market
      dockerfile: ./order_service/Dockerfile
    container_name: order_service
    environment:
      SERVICE_CONFIG_PATH: ./configs/config.yaml
    depends_on:
      - orders_db
    restart: "always"

  orders_db:
    image: postgres:14-alpine
    container_name: orders_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: orders
    ports:
      - "5434:5432"
    volumes:
      - orders_db_data:/var/lib/postgresql/data
      - ./market/database/order:/docker-entrypoint-initdb.d
    restart: "always" 

volumes:
  products_db_data:
  auth_db_data:
  orders_db_data: