proxies:
  - url: http://products:8088
    endpint: payment 
  - url: http://orders:8889
    endpint: present

server:
  address: "0.0.0.0:8080"
  readtimeout: 5s        
  writetimeout: 10s      
  shutdowntime: 15s     
    