proxies:
  - url: http://product:8088
    endpint: products
  - url: http://order:8089
    endpint: orders
  - url: http://auth:8081
    endpint: auth

server:
  address: "0.0.0.0:8080"
  readtimeout: 5s
  writetimeout: 10s
  shutdowntime: 15s
